gameoflife:
  asexualCellsCount: 2
  tStarve: 2000
  sexualCellsCount: 1
  tFullVariance: 600
  tFull: 1000
  reproductionThreshold: 3

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html #http://localhost:8080/swagger-ui.html