gameoflife:
  asexualCellsCount: 6
  sexualCellsCount: 5
  tFull: 1000
  tStarve: 2000
  tFullVariance: 600
  reproductionThreshold: 3

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html #http://localhost:8080/swagger-ui.html