gameoflife:
  sexualCellsCount: 2
  asexualCellsCount: 1
  reproductionThreshold: 4
  startFood: 200
  timeStarve: 2000
  timeFullVariance: 600
  timeFull: 1000
  foodAmountAfterDeath: 7
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
