gameoflife:
  sexualCellsCount: 5
  asexualCellsCount: 6
  reproductionThreshold: 10
  startFood: 10
  tStarve: 2000
  tFullVariance: 600
  tFull: 1000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html #http://localhost:8080/swagger-ui.html
