gameoflife:
  sexualCellsCount: 5
  asexualCellsCount: 6
  reproductionThreshold: 3
  startFood: 100
  timeStarve: 2000
  timeFullVariance: 600
  timeFull: 1000
  foodAmountAfterDeath: 1
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
